defaults:
  - override hydra/job_logging: none


infer_dir: "experiments/all_data/qwen2_5omni/lora_r_64_alpha_128_audio_encoder_trainable_steps_150k_metric_loss_lr_2e-5/infer_step150000"

pred_durations:
  - pred: ${infer_dir}/asvspoof2019.json
    duration: "/mnt/shared-storage-user/xuxuenan/workspace/duplex_training/data/spoofing/asvspoof2019/duration.csv"
  - pred: ${infer_dir}/partial_spoof.json
    duration: "/mnt/shared-storage-user/xuxuenan/workspace/duplex_training/data/spoofing/partial_spoof/duration.csv"
  - pred: ${infer_dir}/sine.json
    duration: "/mnt/shared-storage-user/xuxuenan/workspace/duplex_training/data/spoofing/sine/duration.csv"
  - pred: ${infer_dir}/codecfake_ntu.json
  - pred: ${infer_dir}/partial_edit.json
    duration: "/mnt/shared-storage-user/xuxuenan/workspace/duplex_training/data/spoofing/partial_edit/duration.csv"
  - pred: ${infer_dir}/vctk.json
  - pred: ${infer_dir}/ljspeech.json
  - pred: ${infer_dir}/recent_tts.json
  - pred: ${infer_dir}/wavefake.json


output_file: ${infer_dir}/results/composite.txt

editing_keywords_files:
  - data_json/partial_edit/test.json

hydra:
  output_subdir: null
  run:
    dir: .