defaults:
  - override hydra/job_logging: none

infer_dir: "experiments/all_data/qwen2_5omni/lora_r_64_alpha_128_audio_encoder_trainable_steps_150k_metric_loss_lr_2e-5/infer_step150000"

pred_files:
  - ${infer_dir}/asvspoof2019.json

output_file: ${infer_dir}/results/asvspoof2019.txt


hydra:
  output_subdir: null
  run:
    dir: .
